name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0 # Fetch all history
      - name: Apply configurations
        run: |
          cp quartz.config.ts quartz.layout.ts quartz/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: quartz/package-lock.json
      - name: Install Node.js dependencies
        working-directory: quartz
        run: npm ci --omit=dev
      - name: Build website
        run: npx quartz build --directory ../content --output ../public
        working-directory: quartz
      - name: Upload html files
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: public
